# **Probability and Statistics**

In [0]:
# Modify the empty list, p, so that it becomes a UNIFORM probability
# distribution over n grid cells, as expressed in a list of 
# n probabilities.
def init_distribution(n):
    # Add your code here
    p = [ 1/n for i in range(n) ]
    # End your code here
    return p

In [4]:
init_distribution(5)

[0.2, 0.2, 0.2, 0.2, 0.2]

In [5]:
#Modify the code below so that the function sense, which 
#takes p and Z as inputs, will output the normalized 
#probability distribution, q, after multiplying the entries 
# in p according to the color in the corresponding cell in world,
# followed by normalization of the probability values
world=['green', 'red', 'red', 'green', 'green']
p = [0.2, 0.2, 0.2, 0.2, 0.2]
dictt = {
    "redred": 0.75,
    "redgreen": 0.25,
    "greenred": 0.25,
    "greengreen": 0.75
}

def sense(p, Z):
    # Add your code here
    q = [ p[i] * dictt[Z + world[i]] for i in range(len(p)) ]
    s = sum(q)
    # End your code here
    q = [ i / s for i in q ]
    return q
            
sense(p, 'red')

[0.11111111111111112,
 0.33333333333333337,
 0.33333333333333337,
 0.11111111111111112,
 0.11111111111111112]

In [6]:
#Modify the code so that it updates the probability twice
#and gives the posterior distribution after both 
#measurements are incorporated. Make sure that your code 
#allows for any sequence of measurement of any length.

# DO NOT MODIFY THE SENSE FUNCTION. JUST CALL THE SENSE FUNCTION APPROPRIATELY

p = [0.2, 0.2, 0.2, 0.2, 0.2]
world = ['green', 'red', 'red', 'green', 'green']
measurements = ['red', 'green']

# Add your code here
for i in measurements:
  p = sense(p, i)
# End your code here
print(p)

[0.19999999999999998, 0.19999999999999998, 0.19999999999999998, 0.19999999999999998, 0.19999999999999998]


In [7]:
import numpy as np
#Program a function that returns a new distribution 
#q, shifted to the right by U units. If U=0, q should 
#be the same as p.

def move(p, U):
    # ADD CODE HERE
    for i in range(abs(U)):
      if U >= 0:
        p.insert(0, p.pop())
      else:
        p.append(p.pop(0))
    # END CODE HERE
    return np.array(p)

move([0.11, 0.33, 0.33, 0.11, 0.11], 1)

array([0.11, 0.11, 0.33, 0.33, 0.11])

In [8]:
def move2(p, U):
    q = []
    # ADD CODE HERE
    for i in range(len(p)):
      q.append(p[(len(p) + i - 1)%len(p)] * 0.1 + p[(len(p) + i - 2)%len(p)] * 0.8 + p[(len(p) + i - 3)%len(p)] * 0.1)
    # END CODE HERE
    return q

move2([0, 1.0, 0, 0, 0], 1)

[0.0, 0.0, 0.1, 0.8, 0.1]

In [9]:
# Write code that makes the robot move twice and then prints 
# out the resulting distribution, starting with the initial 
# distribution p = [0, 1, 0, 0, 0]

# Call the function appropriately from here
p = [0, 1.0, 0, 0, 0]
# ADD CODE HERE
for i in range(2):
  p = move2(p, 1)
# END CODE HERE
p

[0.6600000000000001,
 0.16000000000000003,
 0.010000000000000002,
 0.010000000000000002,
 0.16000000000000003]

In [10]:
#write code that moves 1000 times and then prints the 
#resulting probability distribution.

p = [0, 1, 0, 0, 0]
# ADD CODE HERE
for i in range(1000):
  p = move2(p, 1)
# END CODE HERE
p

[0.20000000000000365,
 0.20000000000000373,
 0.20000000000000365,
 0.2000000000000035,
 0.2000000000000035]

In [12]:
#Given the list motions=[1,1] which means the robot 
#moves right and then right again, compute the posterior 
#distribution if the robot first senses red, then moves 
#right one, then senses green, then moves right again, 
#starting with a uniform prior distribution.

world=['green', 'red', 'red', 'green', 'green']
measurements = ['red', 'green']
motions = [1,1]

p = init_distribution(len(world))
# ADD CODE HERE
for i in range(2):
    q = sense(p, measurements[i])
    print(q)
    q1 = move(q, motions[i])
    print(q1)
    p = q1
print(p)

[0.11111111111111112, 0.33333333333333337, 0.33333333333333337, 0.11111111111111112, 0.11111111111111112]
[0.11111111 0.11111111 0.33333333 0.33333333 0.11111111]
[0.15789473684210528, 0.052631578947368425, 0.15789473684210528, 0.47368421052631576, 0.15789473684210528]
[0.15789474 0.15789474 0.05263158 0.15789474 0.47368421]
[0.15789474 0.15789474 0.05263158 0.15789474 0.47368421]
